### travis-ci build fails. It seems to not provide sufficient
### resources (i.e., ram, cpu) to successfully compile, so we
### disable it here
if: false

if: tag =~ /^AO-/

language: shell

os: linux

dist: focal

arch:
  - arm64
# - amd64

services:
  - docker

before_install:
  - cat .travis_dockerfile | docker build -t ao:travis -
  - git switch -c master

script:
  - DEPS="mk-build-deps -i -t 'apt-get --no-install-recommends --yes'"
  - CLEAN="rm -f superslicer-build-deps_*"
  - GBPOPTS="--git-export-dir=artifacts --git-upstream-tree=SLOPPY"
  - BUILD="gbp buildpackage -uc -us -J1 -j1 --git-submodules $GBPOPTS"
  - docker run -v $(pwd):/root ao:travis su -l -c "$DEPS && $CLEAN && $BUILD"

deploy:
  provider: releases
  edge: true
  token: $HIDDEN_TOKEN
  on:
    tags: true
  overwrite: true
  file_glob: true
  file: artifacts/*.{deb,xz,gz,dsc,build,buildinfo,changes}
  prerelease: true
  target_commitish: master
