name: BuildPackage (test)

on:
  workflow_dispatch

jobs:

  amd64_job:

    name: Debian Bullseye (amd64)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          submodules: true

      - name: COMPILE
        uses: ./.github/debian_bullseye/
        with:
          args: >
            /bin/sh -c "
            mk-build-deps -i -t 'apt-get --no-install-recommends --yes' ;
            rm -f superslicer-build-deps_* ;
            GBPOPTS='--git-export-dir=artifacts --git-upstream-tree=SLOPPY' ;
            gbp buildpackage -uc -us -J2 -j2 --git-submodules $GBPOPTS
            "
      - name: DEPLOY
        uses: actions/upload-artifact@v2
        with:
          name: superslicer-debian-bullseye-arm64
          path: |
            artifacts/*.deb
            artifacts/*.xz
            artifacts/*.gz
            artifacts/*.dsc
            artifacts/*.build*
            artifacts/*.changes
